// ── Quantos Wallet Manager ──
// Manages wallet lifecycle: create, import, unlock, lock, sign transactions.
// Wallets are stored encrypted with PIN in chrome.storage.local (extension)
// or localStorage (web app).

import { encryptWithPin, decryptWithPin } from './crypto'
import * as rpc from './rpc'

// ── Types ───────────────────────────────────────────────────

export interface StoredWallet {
  address: string           // hex-encoded 32-byte address
  qtsAddress: string        // qts1... format
  rpcAddress: string        // QTS:<hex> for RPC calls
  publicKey: string         // hex-encoded Dilithium public key
  encryptedSecretKey: string // AES-256-GCM encrypted secret key (base64)
  createdAt: number
}

export interface UnlockedWallet {
  address: string
  qtsAddress: string
  rpcAddress: string        // QTS:<hex> for RPC calls
  publicKey: string
  secretKey: string         // hex-encoded (in memory only, never persisted)
}

export interface WalletStore {
  wallets: StoredWallet[]
  activeAddress: string | null
}

// ── Storage Abstraction ─────────────────────────────────────
// Works with both chrome.storage.local (extension) and localStorage (web)

const STORAGE_KEY = 'quantos_wallets'

function isExtension(): boolean {
  return typeof chrome !== 'undefined' && !!chrome?.storage?.local
}

async function loadStore(): Promise<WalletStore> {
  if (isExtension()) {
    return new Promise((resolve) => {
      chrome.storage.local.get([STORAGE_KEY], (result) => {
        resolve(result[STORAGE_KEY] || { wallets: [], activeAddress: null })
      })
    })
  }
  const raw = localStorage.getItem(STORAGE_KEY)
  return raw ? JSON.parse(raw) : { wallets: [], activeAddress: null }
}

async function saveStore(store: WalletStore): Promise<void> {
  if (isExtension()) {
    return new Promise((resolve) => {
      chrome.storage.local.set({ [STORAGE_KEY]: store }, resolve)
    })
  }
  localStorage.setItem(STORAGE_KEY, JSON.stringify(store))
}

// ── WASM Module ─────────────────────────────────────────────
// Dynamic import of the WASM module (loaded once)

let wasmModule: typeof import('../../pkg/quantos_wallet_core') | null = null

async function getWasm() {
  if (!wasmModule) {
    // @ts-ignore - WASM module is generated by wasm-pack
    const mod = await import('../../pkg/quantos_wallet_core')
    await mod.default() // Initialize WASM
    wasmModule = mod
  }
  return wasmModule
}

// ── Wallet Operations ───────────────────────────────────────

/**
 * Create a new wallet encrypted with PIN.
 * Returns the stored wallet (no secret key exposed).
 */
export async function createWallet(pin: string): Promise<StoredWallet> {
  if (pin.length !== 6 || !/^\d{6}$/.test(pin)) {
    throw new Error('PIN must be exactly 6 digits')
  }

  const wasm = await getWasm()

  // Generate Dilithium-3 keypair
  const keypairJson = wasm.generateKeypair()
  const keypair = JSON.parse(keypairJson) as {
    publicKey: string
    secretKey: string
    address: string
    qtsAddress: string
  }

  // Encrypt secret key with PIN
  const encryptedSecretKey = await encryptWithPin(keypair.secretKey, pin)

  const wallet: StoredWallet = {
    address: keypair.address,
    qtsAddress: keypair.qtsAddress,
    rpcAddress: `QTS:${keypair.address}`,
    publicKey: keypair.publicKey,
    encryptedSecretKey,
    createdAt: Date.now(),
  }

  // Save to storage
  const store = await loadStore()
  store.wallets.push(wallet)
  if (!store.activeAddress) {
    store.activeAddress = wallet.address
  }
  await saveStore(store)

  return wallet
}

/**
 * Import a wallet from a secret key (hex) + PIN.
 * The public key and address are derived from the secret key.
 * Dilithium-3 stores the public key in the last 1952 bytes of the secret key.
 */
export async function importWallet(secretKeyHex: string, pin: string): Promise<StoredWallet> {
  if (pin.length !== 6 || !/^\d{6}$/.test(pin)) {
    throw new Error('PIN must be exactly 6 digits')
  }

  // Validate secret key format (4000 bytes = 8000 hex chars)
  if (secretKeyHex.length !== 8000) {
    throw new Error('Invalid secret key: expected 4000 bytes (8000 hex chars)')
  }

  const wasm = await getWasm()

  // Derive address and public key from secret key using WASM
  // The WASM module extracts the public key from the last 1952 bytes
  const infoJson = wasm.addressFromSecretKey(secretKeyHex)
  const info = JSON.parse(infoJson) as {
    address: string
    publicKey: string
    qtsAddress: string
  }

  // Check if wallet already exists
  const store = await loadStore()
  if (store.wallets.find((w) => w.address === info.address)) {
    throw new Error('Wallet already exists')
  }

  // Encrypt secret key with PIN
  const encryptedSecretKey = await encryptWithPin(secretKeyHex, pin)

  const wallet: StoredWallet = {
    address: info.address,
    qtsAddress: info.qtsAddress,
    rpcAddress: `QTS:${info.address}`,
    publicKey: info.publicKey,
    encryptedSecretKey,
    createdAt: Date.now(),
  }

  // Save to storage
  store.wallets.push(wallet)
  if (!store.activeAddress) {
    store.activeAddress = wallet.address
  }
  await saveStore(store)

  return wallet
}

/**
 * Unlock a wallet with PIN. Returns the unlocked wallet with secret key in memory.
 */
export async function unlockWallet(address: string, pin: string): Promise<UnlockedWallet> {
  const store = await loadStore()
  const wallet = store.wallets.find((w) => w.address === address)

  if (!wallet) {
    throw new Error('Wallet not found')
  }

  // Decrypt secret key with PIN (throws if wrong PIN)
  const secretKey = await decryptWithPin(wallet.encryptedSecretKey, pin)

  return {
    address: wallet.address,
    qtsAddress: wallet.qtsAddress,
    rpcAddress: `QTS:${wallet.address}`,
    publicKey: wallet.publicKey,
    secretKey,
  }
}

/**
 * Get all stored wallets (without secret keys).
 */
export async function getWallets(): Promise<StoredWallet[]> {
  const store = await loadStore()
  return store.wallets
}

/**
 * Get the active wallet address.
 */
export async function getActiveAddress(): Promise<string | null> {
  const store = await loadStore()
  return store.activeAddress
}

/**
 * Set the active wallet.
 */
export async function setActiveWallet(address: string): Promise<void> {
  const store = await loadStore()
  if (!store.wallets.find((w) => w.address === address)) {
    throw new Error('Wallet not found')
  }
  store.activeAddress = address
  await saveStore(store)
}

/**
 * Delete a wallet.
 */
export async function deleteWallet(address: string, pin: string): Promise<void> {
  // Verify PIN first
  await unlockWallet(address, pin)

  const store = await loadStore()
  store.wallets = store.wallets.filter((w) => w.address !== address)
  if (store.activeAddress === address) {
    store.activeAddress = store.wallets[0]?.address || null
  }
  await saveStore(store)
}

/**
 * Check if any wallet exists.
 */
export async function hasWallet(): Promise<boolean> {
  const store = await loadStore()
  return store.wallets.length > 0
}

// ── Transaction: Build + Sign + Broadcast ───────────────────

export interface SendParams {
  to: string            // hex address or qts1... address
  amount: string        // decimal string (in smallest unit, e.g. "1000000" = 1 QTEST)
  gasLimit?: number     // optional, defaults to 21000
  gasPrice?: number     // optional, defaults to 0 (gasless)
}

export interface SendResult {
  txHash: string        // hex transaction hash
  status: 'sent' | 'error'
  error?: string
}

/**
 * Build, sign, and broadcast a transfer transaction.
 * Uses WASM to build+sign (bincode), RPC to broadcast.
 */
export async function sendTransfer(
  wallet: UnlockedWallet,
  params: SendParams,
  rpcUrl?: string,
): Promise<SendResult> {
  try {
    if (rpcUrl) {
      rpc.setRpcUrl(rpcUrl)
    }

    // Get current nonce from node
    const nonce = await rpc.getNonce(wallet.rpcAddress)

    // Get chain info
    const chainId = await rpc.getChainIdNumber()
    const nodeInfo = await rpc.nodeInfo()
    const numShards = nodeInfo.num_shards

    // Resolve destination address
    let toHex = params.to
    if (params.to.startsWith('qts1')) {
      const wasm = await getWasm()
      toHex = wasm.qtsToAddress(params.to)
    }

    // Build and sign transaction with WASM (bincode serialization)
    const wasm = await getWasm()
    const signedJson = wasm.buildSignedTransfer(
      wallet.secretKey,
      toHex,
      params.amount,
      BigInt(nonce),
      BigInt(chainId),
      Number(numShards),
    )
    const signed = JSON.parse(signedJson) as {
      txHex: string
      txHash: string
    }

    // Broadcast via RPC
    const txHash = await rpc.sendRawTransaction(signed.txHex)

    return {
      txHash: rpc.parseQtsRaw(txHash),
      status: 'sent',
    }
  } catch (err) {
    return {
      txHash: '',
      status: 'error',
      error: err instanceof Error ? err.message : 'Unknown error',
    }
  }
}

/**
 * Stake QTEST tokens.
 */
export async function sendStake(
  wallet: UnlockedWallet,
  amount: string,
  rpcUrl?: string,
): Promise<SendResult> {
  try {
    if (rpcUrl) {
      rpc.setRpcUrl(rpcUrl)
    }

    const nonce = await rpc.getNonce(wallet.rpcAddress)
    const chainId = await rpc.getChainIdNumber()
    const nodeInfo = await rpc.nodeInfo()
    const numShards = nodeInfo.num_shards

    const wasm = await getWasm()
    const signedJson = wasm.buildSignedStake(
      wallet.secretKey,
      amount,
      BigInt(nonce),
      BigInt(chainId),
      Number(numShards),
    )
    const signed = JSON.parse(signedJson) as {
      txHex: string
      txHash: string
    }

    const txHash = await rpc.sendRawTransaction(signed.txHex)

    return {
      txHash: rpc.parseQtsRaw(txHash),
      status: 'sent',
    }
  } catch (err) {
    return {
      txHash: '',
      status: 'error',
      error: err instanceof Error ? err.message : 'Unknown error',
    }
  }
}

/**
 * Unstake QTEST tokens.
 */
export async function sendUnstake(
  wallet: UnlockedWallet,
  amount: string,
  rpcUrl?: string,
): Promise<SendResult> {
  try {
    if (rpcUrl) {
      rpc.setRpcUrl(rpcUrl)
    }

    const nonce = await rpc.getNonce(wallet.rpcAddress)
    const chainId = await rpc.getChainIdNumber()
    const nodeInfo = await rpc.nodeInfo()
    const numShards = nodeInfo.num_shards

    const wasm = await getWasm()
    const signedJson = wasm.buildSignedUnstake(
      wallet.secretKey,
      amount,
      BigInt(nonce),
      BigInt(chainId),
      Number(numShards),
    )
    const signed = JSON.parse(signedJson) as {
      txHex: string
      txHash: string
    }

    const txHash = await rpc.sendRawTransaction(signed.txHex)

    return {
      txHash: rpc.parseQtsRaw(txHash),
      status: 'sent',
    }
  } catch (err) {
    return {
      txHash: '',
      status: 'error',
      error: err instanceof Error ? err.message : 'Unknown error',
    }
  }
}

// ── Contract Deploy ──────────────────────────────────────────

export interface DeployParams {
  bytecodeHex: string         // WASM bytecode hex (0x or raw)
  constructorDataHex?: string // ABI-encoded constructor args (optional)
}

/**
 * Build, sign, and broadcast a contract deploy transaction.
 */
export async function deployContract(
  wallet: UnlockedWallet,
  params: DeployParams,
  rpcUrl?: string,
): Promise<SendResult> {
  try {
    if (rpcUrl) {
      rpc.setRpcUrl(rpcUrl)
    }

    const nonce = await rpc.getNonce(wallet.rpcAddress)
    const chainId = await rpc.getChainIdNumber()
    const nodeInfo = await rpc.nodeInfo()
    const numShards = nodeInfo.num_shards

    const wasm = await getWasm()
    const signedJson = wasm.buildSignedDeploy(
      wallet.secretKey,
      params.bytecodeHex,
      params.constructorDataHex || '',
      BigInt(nonce),
      BigInt(chainId),
      Number(numShards),
    )
    const signed = JSON.parse(signedJson) as {
      txHex: string
      txHash: string
    }

    const txHash = await rpc.sendRawTransaction(signed.txHex)

    return {
      txHash: rpc.parseQtsRaw(txHash),
      status: 'sent',
    }
  } catch (err) {
    return {
      txHash: '',
      status: 'error',
      error: err instanceof Error ? err.message : 'Unknown error',
    }
  }
}

// ── Contract Call ────────────────────────────────────────────

export interface ContractCallParams {
  contractAddress: string   // hex or QTS: address
  calldataHex: string       // ABI-encoded function call (0x or raw)
  amount?: string           // value to send (default "0")
}

/**
 * Build, sign, and broadcast a contract call transaction.
 */
export async function callContract(
  wallet: UnlockedWallet,
  params: ContractCallParams,
  rpcUrl?: string,
): Promise<SendResult> {
  try {
    if (rpcUrl) {
      rpc.setRpcUrl(rpcUrl)
    }

    const nonce = await rpc.getNonce(wallet.rpcAddress)
    const chainId = await rpc.getChainIdNumber()
    const nodeInfo = await rpc.nodeInfo()
    const numShards = nodeInfo.num_shards

    let contractHex = params.contractAddress
    if (params.contractAddress.startsWith('qts1')) {
      const wasmMod = await getWasm()
      contractHex = wasmMod.qtsToAddress(params.contractAddress)
    }

    const wasm = await getWasm()
    const signedJson = wasm.buildSignedContractCall(
      wallet.secretKey,
      contractHex,
      params.calldataHex,
      params.amount || '0',
      BigInt(nonce),
      BigInt(chainId),
      Number(numShards),
    )
    const signed = JSON.parse(signedJson) as {
      txHex: string
      txHash: string
    }

    const txHash = await rpc.sendRawTransaction(signed.txHex)

    return {
      txHash: rpc.parseQtsRaw(txHash),
      status: 'sent',
    }
  } catch (err) {
    return {
      txHash: '',
      status: 'error',
      error: err instanceof Error ? err.message : 'Unknown error',
    }
  }
}

// ── Balance & Account ───────────────────────────────────────

export interface BalanceInfo {
  balance: string       // decimal string
  formatted: string     // human readable (e.g. "1.234567 QTS")
  stake: string         // decimal string
  isValidator: boolean
}

/**
 * Get wallet balance with human readable formatting.
 */
export async function getBalance(
  wallet: UnlockedWallet,
  rpcUrl?: string,
): Promise<BalanceInfo> {
  if (rpcUrl) {
    rpc.setRpcUrl(rpcUrl)
  }

  const [balanceRaw, account] = await Promise.all([
    rpc.getBalance(wallet.rpcAddress),
    rpc.getAccount(wallet.rpcAddress),
  ])

  const balance = rpc.parseQtsHex(balanceRaw).toString()
  const stake = rpc.parseQtsHex(account.stake).toString()

  // Format with 6 decimal places (adjust as needed)
  const formatted = formatQtest(balance)

  return {
    balance,
    formatted,
    stake,
    isValidator: account.is_validator,
  }
}

/**
 * Format QTEST amount from smallest unit to human readable.
 */
export function formatQtest(amount: string, decimals: number = 6): string {
  const value = BigInt(amount)
  const divisor = 10n ** BigInt(decimals)
  const whole = value / divisor
  const fraction = value % divisor
  return `${whole}.${fraction.toString().padStart(decimals, '0')} QTEST`
}

/**
 * Parse human readable QTEST amount to smallest unit.
 */
export function parseQtest(formatted: string): string {
  const [whole, fraction = '0'] = formatted.replace(' QTEST', '').replace(' QTS', '').split('.')
  const decimals = fraction.length
  const value = BigInt(whole) * 10n ** BigInt(decimals) + BigInt(fraction)
  return value.toString()
}

// ── NFTs (QN8) ──────────────────────────────────────────

export type { NFTInfo } from './rpc'

/**
 * Get NFTs owned by a wallet address.
 */
export async function getNFTs(
  wallet: UnlockedWallet,
  collectionAddress?: string,
  rpcUrl?: string,
): Promise<rpc.NFTInfo[]> {
  if (rpcUrl) {
    rpc.setRpcUrl(rpcUrl)
  }
  return rpc.getNFTs(wallet.rpcAddress, collectionAddress)
}

// ── Faucet (QTEST) ──────────────────────────────────────────

/// keccak256("claim()") first 4 bytes
const QTEST_CLAIM_SELECTOR = '4e71d92d'

/**
 * Claim 1 QTEST token from the faucet contract.
 * The contract enforces a 24h cooldown per address.
 */
export async function claimFaucet(
  wallet: UnlockedWallet,
  qtestContractAddress: string,
  rpcUrl?: string,
): Promise<SendResult> {
  return callContract(
    wallet,
    {
      contractAddress: qtestContractAddress,
      calldataHex: QTEST_CLAIM_SELECTOR,
      amount: '0',
    },
    rpcUrl,
  )
}

// ── Message Signing ─────────────────────────────────────────

export interface SignedMessage {
  message: string
  signature: string
  publicKey: string
}

/**
 * Sign an arbitrary message (hex or utf8) with the wallet.
 */
export async function signMessage(
  wallet: UnlockedWallet,
  message: string,
  encoding: 'hex' | 'utf8' = 'utf8',
): Promise<SignedMessage> {
  const wasm = await getWasm()
  const messageHex = encoding === 'hex' ? message : bytesToHex(new TextEncoder().encode(message))
  const signatureHex = wasm.signMessage(messageHex, wallet.secretKey)

  return {
    message,
    signature: signatureHex,
    publicKey: wallet.publicKey,
  }
}

/**
 * Verify a message signature.
 */
export async function verifySignature(
  message: string,
  signature: string,
  publicKey: string,
  encoding: 'hex' | 'utf8' = 'utf8',
): Promise<boolean> {
  const wasm = await getWasm()
  const messageHex = encoding === 'hex' ? message : bytesToHex(new TextEncoder().encode(message))
  return wasm.verifySignature(signature, messageHex, publicKey)
}

// ── Helpers ─────────────────────────────────────────────────

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2)
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16)
  }
  return bytes
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}
