/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MultichainNFTMarketplace {
  export type ListingStruct = {
    listingId: BigNumberish;
    seller: AddressLike;
    nftContract: AddressLike;
    tokenId: BigNumberish;
    amount: BigNumberish;
    standard: BigNumberish;
    paymentToken: AddressLike;
    price: BigNumberish;
    status: BigNumberish;
    expiresAt: BigNumberish;
  };

  export type ListingStructOutput = [
    listingId: bigint,
    seller: string,
    nftContract: string,
    tokenId: bigint,
    amount: bigint,
    standard: bigint,
    paymentToken: string,
    price: bigint,
    status: bigint,
    expiresAt: bigint
  ] & {
    listingId: bigint;
    seller: string;
    nftContract: string;
    tokenId: bigint;
    amount: bigint;
    standard: bigint;
    paymentToken: string;
    price: bigint;
    status: bigint;
    expiresAt: bigint;
  };

  export type OfferStruct = {
    offerId: BigNumberish;
    offerer: AddressLike;
    nftContract: AddressLike;
    tokenId: BigNumberish;
    paymentToken: AddressLike;
    offerPrice: BigNumberish;
    expiresAt: BigNumberish;
    isActive: boolean;
  };

  export type OfferStructOutput = [
    offerId: bigint,
    offerer: string,
    nftContract: string,
    tokenId: bigint,
    paymentToken: string,
    offerPrice: bigint,
    expiresAt: bigint,
    isActive: boolean
  ] & {
    offerId: bigint;
    offerer: string;
    nftContract: string;
    tokenId: bigint;
    paymentToken: string;
    offerPrice: bigint;
    expiresAt: bigint;
    isActive: boolean;
  };
}

export interface MultichainNFTMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FEE"
      | "acceptOffer"
      | "buyNFT"
      | "cancelListing"
      | "cancelOffer"
      | "feeRecipient"
      | "getActiveListings"
      | "getActiveOffers"
      | "listNFT"
      | "listings"
      | "makeOffer"
      | "marketplaceFee"
      | "nftListings"
      | "nftOffers"
      | "offers"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "onERC721Received"
      | "owner"
      | "renounceOwnership"
      | "setFeeRecipient"
      | "setMarketplaceFee"
      | "supportsInterface"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeRecipientUpdated"
      | "Listed"
      | "ListingCancelled"
      | "MarketplaceFeeUpdated"
      | "OfferAccepted"
      | "OfferCancelled"
      | "OfferMade"
      | "OwnershipTransferred"
      | "Sale"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MAX_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveListings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOffers",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listNFT",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeOffer",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplaceFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftListings",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nftOffers",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketplaceFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "makeOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplaceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftOffers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "offers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketplaceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FeeRecipientUpdatedEvent {
  export type InputTuple = [newRecipient: AddressLike];
  export type OutputTuple = [newRecipient: string];
  export interface OutputObject {
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    seller: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish,
    amount: BigNumberish,
    standard: BigNumberish,
    paymentToken: AddressLike,
    price: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    seller: string,
    nftContract: string,
    tokenId: bigint,
    amount: bigint,
    standard: bigint,
    paymentToken: string,
    price: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
    nftContract: string;
    tokenId: bigint;
    amount: bigint;
    standard: bigint;
    paymentToken: string;
    price: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCancelledEvent {
  export type InputTuple = [listingId: BigNumberish];
  export type OutputTuple = [listingId: bigint];
  export interface OutputObject {
    listingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketplaceFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferAcceptedEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    seller: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [offerId: bigint, seller: string, price: bigint];
  export interface OutputObject {
    offerId: bigint;
    seller: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferCancelledEvent {
  export type InputTuple = [offerId: BigNumberish];
  export type OutputTuple = [offerId: bigint];
  export interface OutputObject {
    offerId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferMadeEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    offerer: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish,
    paymentToken: AddressLike,
    offerPrice: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    offerer: string,
    nftContract: string,
    tokenId: bigint,
    paymentToken: string,
    offerPrice: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    offerer: string;
    nftContract: string;
    tokenId: bigint;
    paymentToken: string;
    offerPrice: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish,
    amount: BigNumberish,
    price: BigNumberish,
    marketplaceFeeAmount: BigNumberish,
    royaltyAmount: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    seller: string,
    nftContract: string,
    tokenId: bigint,
    amount: bigint,
    price: bigint,
    marketplaceFeeAmount: bigint,
    royaltyAmount: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    seller: string;
    nftContract: string;
    tokenId: bigint;
    amount: bigint;
    price: bigint;
    marketplaceFeeAmount: bigint;
    royaltyAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultichainNFTMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): MultichainNFTMarketplace;
  waitForDeployment(): Promise<this>;

  interface: MultichainNFTMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FEE: TypedContractMethod<[], [bigint], "view">;

  acceptOffer: TypedContractMethod<
    [offerId: BigNumberish, standard: BigNumberish],
    [void],
    "nonpayable"
  >;

  buyNFT: TypedContractMethod<[listingId: BigNumberish], [void], "payable">;

  cancelListing: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelOffer: TypedContractMethod<
    [offerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getActiveListings: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [MultichainNFTMarketplace.ListingStructOutput[]],
    "view"
  >;

  getActiveOffers: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [MultichainNFTMarketplace.OfferStructOutput[]],
    "view"
  >;

  listNFT: TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      amount: BigNumberish,
      standard: BigNumberish,
      paymentToken: AddressLike,
      price: BigNumberish,
      expiresAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        listingId: bigint;
        seller: string;
        nftContract: string;
        tokenId: bigint;
        amount: bigint;
        standard: bigint;
        paymentToken: string;
        price: bigint;
        status: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  makeOffer: TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      paymentToken: AddressLike,
      offerPrice: BigNumberish,
      expiresAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  marketplaceFee: TypedContractMethod<[], [bigint], "view">;

  nftListings: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  nftOffers: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  offers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint, boolean] & {
        offerId: bigint;
        offerer: string;
        nftContract: string;
        tokenId: bigint;
        paymentToken: string;
        offerPrice: bigint;
        expiresAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  onERC1155BatchReceived: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  onERC1155Received: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setMarketplaceFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOffer"
  ): TypedContractMethod<
    [offerId: BigNumberish, standard: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyNFT"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOffer"
  ): TypedContractMethod<[offerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveListings"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [MultichainNFTMarketplace.ListingStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveOffers"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [MultichainNFTMarketplace.OfferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "listNFT"
  ): TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      amount: BigNumberish,
      standard: BigNumberish,
      paymentToken: AddressLike,
      price: BigNumberish,
      expiresAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        listingId: bigint;
        seller: string;
        nftContract: string;
        tokenId: bigint;
        amount: bigint;
        standard: bigint;
        paymentToken: string;
        price: bigint;
        status: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "makeOffer"
  ): TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      paymentToken: AddressLike,
      offerPrice: BigNumberish,
      expiresAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "marketplaceFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftListings"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nftOffers"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "offers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint, boolean] & {
        offerId: bigint;
        offerer: string;
        nftContract: string;
        tokenId: bigint;
        paymentToken: string;
        offerPrice: bigint;
        expiresAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC1155BatchReceived"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC1155Received"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketplaceFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeeRecipientUpdated"
  ): TypedContractEvent<
    FeeRecipientUpdatedEvent.InputTuple,
    FeeRecipientUpdatedEvent.OutputTuple,
    FeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Listed"
  ): TypedContractEvent<
    ListedEvent.InputTuple,
    ListedEvent.OutputTuple,
    ListedEvent.OutputObject
  >;
  getEvent(
    key: "ListingCancelled"
  ): TypedContractEvent<
    ListingCancelledEvent.InputTuple,
    ListingCancelledEvent.OutputTuple,
    ListingCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketplaceFeeUpdated"
  ): TypedContractEvent<
    MarketplaceFeeUpdatedEvent.InputTuple,
    MarketplaceFeeUpdatedEvent.OutputTuple,
    MarketplaceFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OfferAccepted"
  ): TypedContractEvent<
    OfferAcceptedEvent.InputTuple,
    OfferAcceptedEvent.OutputTuple,
    OfferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "OfferCancelled"
  ): TypedContractEvent<
    OfferCancelledEvent.InputTuple,
    OfferCancelledEvent.OutputTuple,
    OfferCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OfferMade"
  ): TypedContractEvent<
    OfferMadeEvent.InputTuple,
    OfferMadeEvent.OutputTuple,
    OfferMadeEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Sale"
  ): TypedContractEvent<
    SaleEvent.InputTuple,
    SaleEvent.OutputTuple,
    SaleEvent.OutputObject
  >;

  filters: {
    "FeeRecipientUpdated(address)": TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;
    FeeRecipientUpdated: TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;

    "Listed(uint256,address,address,uint256,uint256,uint8,address,uint256,uint256)": TypedContractEvent<
      ListedEvent.InputTuple,
      ListedEvent.OutputTuple,
      ListedEvent.OutputObject
    >;
    Listed: TypedContractEvent<
      ListedEvent.InputTuple,
      ListedEvent.OutputTuple,
      ListedEvent.OutputObject
    >;

    "ListingCancelled(uint256)": TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
    ListingCancelled: TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;

    "MarketplaceFeeUpdated(uint256)": TypedContractEvent<
      MarketplaceFeeUpdatedEvent.InputTuple,
      MarketplaceFeeUpdatedEvent.OutputTuple,
      MarketplaceFeeUpdatedEvent.OutputObject
    >;
    MarketplaceFeeUpdated: TypedContractEvent<
      MarketplaceFeeUpdatedEvent.InputTuple,
      MarketplaceFeeUpdatedEvent.OutputTuple,
      MarketplaceFeeUpdatedEvent.OutputObject
    >;

    "OfferAccepted(uint256,address,uint256)": TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;
    OfferAccepted: TypedContractEvent<
      OfferAcceptedEvent.InputTuple,
      OfferAcceptedEvent.OutputTuple,
      OfferAcceptedEvent.OutputObject
    >;

    "OfferCancelled(uint256)": TypedContractEvent<
      OfferCancelledEvent.InputTuple,
      OfferCancelledEvent.OutputTuple,
      OfferCancelledEvent.OutputObject
    >;
    OfferCancelled: TypedContractEvent<
      OfferCancelledEvent.InputTuple,
      OfferCancelledEvent.OutputTuple,
      OfferCancelledEvent.OutputObject
    >;

    "OfferMade(uint256,address,address,uint256,address,uint256,uint256)": TypedContractEvent<
      OfferMadeEvent.InputTuple,
      OfferMadeEvent.OutputTuple,
      OfferMadeEvent.OutputObject
    >;
    OfferMade: TypedContractEvent<
      OfferMadeEvent.InputTuple,
      OfferMadeEvent.OutputTuple,
      OfferMadeEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Sale(uint256,address,address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SaleEvent.InputTuple,
      SaleEvent.OutputTuple,
      SaleEvent.OutputObject
    >;
    Sale: TypedContractEvent<
      SaleEvent.InputTuple,
      SaleEvent.OutputTuple,
      SaleEvent.OutputObject
    >;
  };
}
